// <auto-generated />
using System;
using Cashier;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cashier.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cashier.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("No_Telp")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Cashier.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Cashier.Model.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PelangganId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tanggal_jual")
                        .HasColumnType("date");

                    b.Property<decimal>("Total_Harga")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PelangganId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Cashier.Model.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JualId")
                        .HasColumnType("integer");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdukId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotalHarga")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("JualId");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("ProdukId");

                    b.ToTable("SalesDetails");
                });

            modelBuilder.Entity("Cashier.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("No_Telp")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cashier.Model.Sale", b =>
                {
                    b.HasOne("Cashier.Model.Customer", "Pelanggan")
                        .WithMany()
                        .HasForeignKey("PelangganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelanggan");
                });

            modelBuilder.Entity("Cashier.Model.SaleDetail", b =>
                {
                    b.HasOne("Cashier.Model.Sale", "Jual")
                        .WithMany()
                        .HasForeignKey("JualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cashier.Model.User", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cashier.Model.Product", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jual");

                    b.Navigation("Pengguna");

                    b.Navigation("Produk");
                });
#pragma warning restore 612, 618
        }
    }
}
